name: Terraform apply
on:
  push:
    branches:
      - 'main'
jobs:
  apply_tf_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_TRIAL_SERVICE_ACCOUNT_KEY }}
      - name: terraform apply
        id: apply
        run: terraform apply -no-color -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.TERRAFORM_TRIAL_SERVICE_ACCOUNT_KEY }}
